// AI-Generated Average Load Test - 200 Virtual Users
// Generated by AI Performance Testing Assistant
// Duration: 15 minutes with ramp-up and ramp-down

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

const loginFailureRate = new Rate('login_failures');
const checkoutSuccessRate = new Rate('checkout_success');
const businessTransactionDuration = new Trend('business_transaction_duration');
const errorCount = new Counter('errors');
const apiResponseTime = new Trend('api_response_time');

export const options = {
  stages: [
    { duration: '3m', target: 50 },
    { duration: '2m', target: 100 },
    { duration: '5m', target: 200 },
    { duration: '3m', target: 100 },
    { duration: '2m', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<5000'],
    http_req_failed: ['rate<0.10'],
    checkout_success: ['rate>0.85'],
    api_response_time: ['p(95)<3000'],
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:5000';

const productSlugs = [
  'smartphone-pro-x', 'laptop-ultra-15', 'wireless-headphones',
  'tablet-pro-12', 'gaming-console', 'digital-camera',
  'mechanical-keyboard', 'monitor-27-4k', 'ssd-1tb-external',
  'running-shoes', 'denim-jeans', 'winter-jacket',
  'yoga-mat-premium', 'dumbbell-set-20lbs', 'fitness-tracker',
  'board-game-collection', 'building-blocks-500pc',
  'air-purifier', 'robot-vacuum', 'coffee-maker-pro',
];

export default function () {
  const transactionStart = Date.now();

  group('E-Commerce Business Flow', () => {
    // Register/Login
    const email = `load_${Date.now()}_${Math.random().toString(36).substring(7)}@test.com`;
    let authRes = http.post(`${BASE_URL}/api/auth/register`, JSON.stringify({
      email: email,
      password: 'password123',
      first_name: 'Load',
      last_name: `User_${Math.floor(Math.random() * 1000)}`,
    }), { headers: { 'Content-Type': 'application/json' } });

    if (authRes.status !== 201) {
      authRes = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify({
        email: 'john@example.com',
        password: 'password123',
      }), { headers: { 'Content-Type': 'application/json' } });
    }

    loginFailureRate.add(authRes.status !== 200 && authRes.status !== 201);

    const token = authRes.json('token');
    const headers = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
    };

    if (!token) {
      errorCount.add(1);
      sleep(1);
      return;
    }

    // Browse categories
    let categoriesRes = http.get(`${BASE_URL}/api/products/categories`, headers);
    apiResponseTime.add(Date.now() - transactionStart);
    sleep(0.5);

    // Search products
    const searchTerms = ['laptop', 'phone', 'shoes', 'book', 'game', 'watch', 'camera', 'headphone'];
    const searchTerm = searchTerms[Math.floor(Math.random() * searchTerms.length)];
    let searchRes = http.get(`${BASE_URL}/api/products?q=${searchTerm}&limit=20`, headers);
    check(searchRes, { 'search successful': (r) => r.status === 200 });
    apiResponseTime.add(Date.now() - transactionStart);
    sleep(0.3);

    // View multiple products
    const numProducts = Math.floor(Math.random() * 3) + 1;
    for (let i = 0; i < numProducts; i++) {
      const slug = productSlugs[Math.floor(Math.random() * productSlugs.length)];
      let productRes = http.get(`${BASE_URL}/api/products/${slug}`, headers);
      check(productRes, { 'product detail loaded': (r) => r.status === 200 });

      if (productRes.status === 200 && i === 0) {
        let productId = productRes.json('id');
        if (productId) {
          // Add to cart
          let cartRes = http.post(`${BASE_URL}/api/cart`, JSON.stringify({
            product_id: productId,
            quantity: Math.floor(Math.random() * 3) + 1,
          }), headers);
          check(cartRes, { 'added to cart': (r) => r.status === 200 });
        }
      }
      sleep(0.2);
    }

    // View cart
    let cartRes = http.get(`${BASE_URL}/api/cart`, headers);
    check(cartRes, { 'cart retrieved': (r) => r.status === 200 });

    // Checkout (30% of users complete purchase)
    if (Math.random() < 0.3) {
      let checkoutRes = http.post(`${BASE_URL}/api/orders`, JSON.stringify({
        shipping_address: {
          street: `${Math.floor(Math.random() * 9999) + 1} Performance Blvd`,
          city: 'Load City',
          state: 'TS',
          zip: '12345',
          country: 'US',
        },
        payment_method: Math.random() < 0.5 ? 'credit_card' : 'paypal',
      }), headers);

      const success = check(checkoutRes, {
        'checkout successful': (r) => r.status === 201,
      });
      checkoutSuccessRate.add(success);
      if (!success) errorCount.add(1);
    }

    // Check orders
    if (Math.random() < 0.5) {
      let ordersRes = http.get(`${BASE_URL}/api/orders`, headers);
      check(ordersRes, { 'orders retrieved': (r) => r.status === 200 });
    }
  });

  businessTransactionDuration.add(Date.now() - transactionStart);
  sleep(Math.random() * 2 + 0.5);
}
