// AI-Generated Black Friday Simulation - 1000 Virtual Users
// Generated by AI Performance Testing Assistant
// Extreme peak traffic scenario with stress conditions

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter, Gauge } from 'k6/metrics';

const errorRate = new Rate('error_rate');
const orderSuccessRate = new Rate('order_success_rate');
const endpointLatency = new Trend('endpoint_latency');
const concurrentUsers = new Gauge('concurrent_users');
const errorCount = new Counter('error_count');

export const options = {
  stages: [
    { duration: '2m', target: 200 },
    { duration: '3m', target: 500 },
    { duration: '5m', target: 1000 },
    { duration: '3m', target: 500 },
    { duration: '2m', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(90)<12000', 'p(95)<15000'],
    http_req_failed: ['rate<0.20'],
    order_success_rate: ['rate>0.50'],
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:5000';

export default function () {
  concurrentUsers.add(__VU);

  group('Black Friday Shopping Spree', () => {
    const email = `bf_${__VU}_${Date.now()}@blackfriday.com`;
    
    // User registration
    let regRes = http.post(`${BASE_URL}/api/auth/register`, JSON.stringify({
      email: email,
      password: 'password123',
      first_name: 'Black',
      last_name: `Friday_${__VU}`,
    }), { headers: { 'Content-Type': 'application/json' } });

    let token = regRes.json('token');
    
    if (regRes.status !== 201 || !token) {
      // Login fallback
      let loginRes = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify({
        email: 'john@example.com',
        password: 'password123',
      }), { headers: { 'Content-Type': 'application/json' } });
      token = loginRes.json('token');
    }

    if (!token) {
      errorRate.add(1);
      errorCount.add(1);
      sleep(0.2);
      return;
    }

    const headers = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
    };

    // Aggressive shopping behavior
    const browseStart = Date.now();
    
    // Quick product search
    let prodRes = http.get(`${BASE_URL}/api/products?limit=10`, headers);
    endpointLatency.add(Date.now() - browseStart);
    check(prodRes, { 'products loaded': (r) => r.status === 200 });

    // Rapid add to cart
    if (prodRes.status === 200 && prodRes.json('products')?.length > 0) {
      const product = prodRes.json('products')[0];
      let cartRes = http.post(`${BASE_URL}/api/cart`, JSON.stringify({
        product_id: product.id,
        quantity: 1,
      }), headers);

      if (cartRes.status === 200) {
        // Immediate checkout
        let checkoutRes = http.post(`${BASE_URL}/api/orders`, JSON.stringify({
          shipping_address: {
            street: `123 Black Friday Ln`,
            city: 'Deal City',
            state: 'BF',
            zip: '99999',
            country: 'US',
          },
          payment_method: 'credit_card',
        }), headers);

        const success = check(checkoutRes, {
          'order placed successfully': (r) => r.status === 201,
        });
        orderSuccessRate.add(success);

        if (!success) {
          errorRate.add(1);
          errorCount.add(1);
        }
      }
    }
  });

  sleep(0.1);
}

export function teardown(data) {
  console.log(`Black Friday test completed. Error rate: ${errorRate}`);
}
