// AI-Generated Peak Load Test - 500 Virtual Users
// Generated by AI Performance Testing Assistant  
// Simulates Flash Sale / Peak Traffic Scenario

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

const failureRate = new Rate('failure_rate');
const checkoutRate = new Rate('checkout_rate');
const transactionTime = new Trend('transaction_time');
const errorCounter = new Counter('total_errors');

export const options = {
  stages: [
    { duration: '2m', target: 100 },
    { duration: '3m', target: 300 },
    { duration: '5m', target: 500 },
    { duration: '3m', target: 300 },
    { duration: '2m', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(90)<8000', 'p(95)<10000'],
    http_req_failed: ['rate<0.15'],
    checkout_rate: ['rate>0.70'],
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:5000';

const productSlugs = [
  'smartphone-pro-x', 'laptop-ultra-15', 'wireless-headphones',
  'smart-watch', 'tablet-pro-12', 'bluetooth-speaker',
  'gaming-console', 'digital-camera', 'portable-charger',
  'usb-c-hub', 'cotton-t-shirt', 'denim-jeans',
  'winter-jacket', 'running-shoes', 'leather-belt',
  'garden-tool-set', 'indoor-plant-pot', 'led-desk-lamp',
  'smart-thermostat', 'cookware-set', 'programming-book',
  'design-patterns', 'data-science-guide', 'business-strategy',
  'cookbook-deluxe', 'yoga-mat-premium', 'dumbbell-set-20lbs',
  'resistance-bands', 'water-bottle-insulated', 'fitness-tracker',
  'board-game-collection', 'building-blocks-500pc', 'remote-control-car',
  'puzzle-1000pc', 'stuffed-animal-bear', 'mechanical-keyboard',
  'webcam-hd-4k', 'wireless-mouse', 'monitor-27-4k',
  'ssd-1tb-external', 'wool-sweater', 'casual-sneakers',
  'formal-shirt', 'winter-gloves', 'cashmere-scarf',
  'air-purifier', 'robot-vacuum', 'coffee-maker-pro',
  'electric-kettle', 'throw-blanket',
];

export default function () {
  const start = Date.now();

  group('Peak Shopping Flow', () => {
    // Quick login with pre-created test accounts
    const userId = Math.floor(Math.random() * 1000) + 100;
    const email = `peak_user_${userId}@test.com`;
    
    let authRes = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify({
      email: email,
      password: 'password123',
    }), { headers: { 'Content-Type': 'application/json' }, tags: { name: 'Login' } });

    if (authRes.status !== 200) {
      authRes = http.post(`${BASE_URL}/api/auth/register`, JSON.stringify({
        email: email,
        password: 'password123',
        first_name: 'Peak',
        last_name: `User${userId}`,
      }), { headers: { 'Content-Type': 'application/json' }, tags: { name: 'Register' } });
    }

    const token = authRes.json('token');
    if (!token) {
      errorCounter.add(1);
      sleep(0.5);
      return;
    }

    const authHeaders = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      tags: { name: 'AuthenticatedRequest' },
    };

    // Browse flash sale products
    let searchRes = http.get(`${BASE_URL}/api/products?limit=20&sort_by=price&sort_order=desc`, authHeaders);
    check(searchRes, { 'browse successful': (r) => r.status === 200 });

    // Add items to cart (flash sale - high intent)
    const itemsToAdd = Math.floor(Math.random() * 3) + 1;
    for (let i = 0; i < itemsToAdd; i++) {
      let productRes = http.get(`${BASE_URL}/api/products?limit=1`, authHeaders);
      if (productRes.status === 200 && productRes.json('products')?.length > 0) {
        const product = productRes.json('products')[0];
        http.post(`${BASE_URL}/api/cart`, JSON.stringify({
          product_id: product.id,
          quantity: 1,
        }), authHeaders);
      }
    }

    // High checkout rate during peak
    if (Math.random() < 0.4) {
      let checkoutRes = http.post(`${BASE_URL}/api/orders`, JSON.stringify({
        shipping_address: {
          street: `${Math.floor(Math.random() * 9999) + 1} Flash Sale St`,
          city: 'Peak City',
          state: 'PK',
          zip: '54321',
          country: 'US',
        },
        payment_method: 'credit_card',
      }), authHeaders);

      const success = check(checkoutRes, {
        'checkout completed': (r) => r.status === 201,
      });
      checkoutRate.add(success);
      if (!success) {
        failureRate.add(1);
        errorCounter.add(1);
      }
    }
  });

  transactionTime.add(Date.now() - start);
  sleep(0.5);
}
