// AI-Generated Smoke Test - 50 Virtual Users
// Generated by AI Performance Testing Assistant
// Test Scenario: Login -> Search -> Product Detail -> Add to Cart -> Checkout

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

// Custom metrics
const loginFailureRate = new Rate('login_failures');
const checkoutSuccessRate = new Rate('checkout_success');
const businessTransactionDuration = new Trend('business_transaction_duration');
const errorCount = new Counter('errors');

export const options = {
  vus: 50,
  duration: '30s',
  thresholds: {
    http_req_duration: ['p(95)<2000'],
    http_req_failed: ['rate<0.05'],
    login_failures: ['rate<0.02'],
    checkout_success: ['rate>0.95'],
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:5000';

function getRandomProduct() {
  const products = [
    'smartphone-pro-x', 'laptop-ultra-15', 'wireless-headphones',
    'tablet-pro-12', 'gaming-console', 'mechanical-keyboard',
    'running-shoes', 'yoga-mat-premium', 'board-game-collection',
  ];
  return products[Math.floor(Math.random() * products.length)];
}

export default function () {
  const transactionStart = Date.now();

  group('Complete Business Transaction', () => {
    // Step 1: Login with pre-seeded test accounts
    const testAccounts = [
      { email: 'john@example.com', password: 'password123' },
      { email: 'jane@example.com', password: 'password123' },
      { email: 'bob@example.com', password: 'password123' },
    ];
    const account = testAccounts[Math.floor(Math.random() * testAccounts.length)];

    let loginRes = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify(account), {
      headers: { 'Content-Type': 'application/json' },
    });

    check(loginRes, {
      'login successful': (r) => r.status === 200,
    });
    loginFailureRate.add(loginRes.status !== 200);

    let token = loginRes.json('token');

    if (!token) {
      errorCount.add(1);
      sleep(1);
      return;
    }

    const authHeaders = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
    };

    // Step 2: Search Products
    let searchRes = http.get(`${BASE_URL}/api/products?q=laptop&limit=10`, authHeaders);
    check(searchRes, {
      'search returns results': (r) => r.status === 200,
    });

    sleep(0.3);

    // Step 3: View Product Detail
    const productSlug = getRandomProduct();
    let productRes = http.get(`${BASE_URL}/api/products/${productSlug}`, authHeaders);
    check(productRes, {
      'product detail loaded': (r) => r.status === 200,
    });

    sleep(0.3);

    // Step 4: Add to Cart
    let productId = productRes.json('id');
    let cartRes = http.post(`${BASE_URL}/api/cart`, JSON.stringify({
      product_id: productId,
      quantity: 1,
    }), authHeaders);
    check(cartRes, {
      'added to cart': (r) => r.status === 200,
    });

    sleep(0.3);

    // Step 5: Checkout
    let checkoutRes = http.post(`${BASE_URL}/api/orders`, JSON.stringify({
      shipping_address: {
        street: '123 Test St',
        city: 'Load City',
        state: 'TS',
        zip: '12345',
        country: 'US',
      },
      payment_method: 'credit_card',
    }), authHeaders);

    const checkoutSuccess = check(checkoutRes, {
      'checkout successful': (r) => r.status === 201,
    });
    checkoutSuccessRate.add(checkoutSuccess);

    if (!checkoutSuccess) {
      errorCount.add(1);
    }
  });

  businessTransactionDuration.add(Date.now() - transactionStart);
  sleep(1);
}
